import os, subprocess

def get_formants_sl(filepath):

    script = open("GetFormants.praat", 'w')
    script.write('Read from file: "{!s}"\r\n'.format(soundfile))
    script.write('To Formant (burg): 0, 5, 5500, {!s}, 50\r\n'.format(TargetLength))
    script.write('List: "no", "yes", 6, "no", 3, "no", 3, "no"\r\n')
    script.write('appendFile ("formants.txt", info$ ())')
    script.close()



def get_formants_sl2(name, directory, currentgeneration, samplerate):
    """ Opens the pitch.txt file generated by PRAAT

    returns: a list of the first five formant frequencies
    """

    script = open("GetPitch.praat", 'w')
    script.write('Read from file: "{!s}"\r\n'.format(soundfile))
    script.write('To Pitch: {!s}, 75, 600\r\n'.format(TargetLength))
    script.write('Get mean: 0, 0, "Hertz"\r\n')
    script.write('appendFile ("pitch.txt", info$ ())')
    script.close()

    subprocess.call(['./praat', '--ansi', '--run', 'GetPitch.praat'], stdout=subprocess.DEVNULL)
    os.remove('GetPitch.praat')

    script = open("GetFormants.praat", 'w')
    script.write('Read from file: "{!s}"\r\n'.format(soundfile))
    script.write('To Formant (burg): 0, 5, 5500, {!s}, 50\r\n'.format(TargetLength))
    script.write('List: "no", "yes", 6, "no", 3, "no", 3, "no"\r\n')
    script.write('appendFile ("formants.txt", info$ ())')
    script.close()

    subprocess.call(['./praat', '--ansi','--run', 'GetFormants.praat'], stdout=subprocess.DEVNULL)
    os.remove('GetFormants.praat')
    
    # Opens text file with formant information as the var .formants
    with open("{}/Generation{!s}/formants{!s}.txt".format(directory, currentgeneration, name), "r") as formants:
        # Splits the lines of the text file into items of a list in .lines
        lines = formants.readlines()

    # Assigns the second item from .lines to candformants
    candformants = lines[1].split("\t")

    # print('candformants', candformants)
    
    # Strips whitespace and checks if a formant is undefined and sets this to half the sample rate
    for i in range(len(candformants)):
        candformants[i] = candformants[i].strip()
        if candformants[i].islower():
            candformants[i] = str(samplerate/2)

    # Converts the list of strings to a list of floats
    candformants = list(map(float, candformants))
    
    # print('candformants', candformants)
    
    os.remove("{}/Generation{!s}/formants{!s}.txt".format(directory, currentgeneration, name))

    return candformants[1:6]