PRT_PARAMETER_DEFS = {'ALL':
                   ['Cricothyroid',
                    'Vocalis',
                    'Thyroarytenoid',
                    'PosteriorCricoarytenoid',
                    'LateralCricoarytenoid',
                    'Stylohyoid',
                    'Sternohyoid',
                    'Thyropharyngeus',
                    'LowerConstrictor',
                    'MiddleConstrictor',
                    'UpperConstrictor',
                    'Sphincter',
                    'Hyoglossus',
                    'Styloglossus',
                    'Genioglossus',
                    'UpperTongue',
                    'LowerTongue',
                    'TransverseTongue',
                    'VerticalTongue',
                    'Risorius',
                    'OrbicularisOris',
                    'TensorPalatini',
                    'Masseter',
                    'Mylohyoid',
                    'LateralPterygoid',
                    'Buccinator'],
                   'CONSTRAINED':
                   ['Hyoglossus',
                    'Styloglossus',
                    'Genioglossus',
                    'UpperTongue',
                    'LowerTongue',
                    'TransverseTongue',
                    'VerticalTongue',
                    'Risorius',
                    'OrbicularisOris',
                    'TensorPalatini',
                    'Masseter',
                    'Mylohyoid',
                    'LateralPterygoid',
                    'Buccinator']
                   }

VTL_PARAMETER_DEFS = {'ALL':
                      [('HX', 0.0, 1.0),
                       ('HY', -6.0, -3.5),
                       ('JX', -0.5, 0.0),
                       ('JA', -7.0, 0.0),
                       ('LP', -1.0, 1.0),
                       ('LD', -2.0, 4.0),
                       ('VS',  0.0, 1.0),
                       ('VO', -0.1, 1.0),
                       ('TCX', -3.0, 4.0),
                       ('TCY', -3.0, 1.0),
                       ('TTX', 1.5, 5.5),
                       ('TTY', -3.0, 2.5),
                       ('TBX', -3.0, 4.0),
                       ('TBY', -3.0, 5.0),
                       ('TRX', -4.0, 2.0),
                       ('TRY', -6.0, 0.0),
                       ('TS1', 0.0, 1.0),
                       ('TS2', 0.0, 1.0),
                       ('TS3', -1.0, 1.0)
                       ]
                      }
