PRT_PARAMETER_DEFS = {'ALL':
                      [('Cricothyroid', -1.0, 1.0),
                       ('Vocalis', -1.0, 1.0),
                       ('Thyroarytenoid', -1.0, 1.0),
                       ('PosteriorCricoarytenoid', -1.0, 1.0),
                       ('LateralCricoarytenoid', -1.0, 1.0),
                       ('Stylohyoid', -1.0, 1.0),
                       ('Sternohyoid', -1.0, 1.0),
                       ('Thyropharyngeus', -1.0, 1.0),
                       ('LowerConstrictor', -1.0, 1.0),
                       ('MiddleConstrictor', -1.0, 1.0),
                       ('UpperConstrictor', -1.0, 1.0),
                       ('Sphincter', -1.0, 1.0),
                       ('Hyoglossus', -1.0, 1.0),
                       ('Styloglossus', -1.0, 1.0),
                       ('Genioglossus', -1.0, 1.0),
                       ('UpperTongue', -1.0, 1.0),
                       ('LowerTongue', -1.0, 1.0),
                       ('TransverseTongue', -1.0, 1.0),
                       ('VerticalTongue', -1.0, 1.0),
                       ('Risorius', -1.0, 1.0),
                       ('OrbicularisOris', -1.0, 1.0),
                       ('TensorPalatini', -1.0, 1.0),
                       ('Masseter', -1.0, 1.0),
                       ('Mylohyoid', -1.0, 1.0),
                       ('LateralPterygoid', -1.0, 1.0),
                       ('Buccinator', -1.0, 1.0)],

                      'CONSTRAINED':
                      [('Hyoglossus', -1.0, 1.0),
                       ('Styloglossus', -1.0, 1.0),
                       ('Genioglossus', -1.0, 1.0),
                       ('UpperTongue', -1.0, 1.0),
                       ('LowerTongue', -1.0, 1.0),
                       ('TransverseTongue', -1.0, 1.0),
                       ('VerticalTongue', -1.0, 1.0),
                       ('Risorius', -1.0, 1.0),
                       ('OrbicularisOris', -1.0, 1.0),
                       ('TensorPalatini', -1.0, 1.0),
                       ('Masseter', -1.0, 1.0),
                       ('Mylohyoid', -1.0, 1.0),
                       ('LateralPterygoid', -1.0, 1.0),
                       ('Buccinator', 1.0, 1.0)]
                      }

VTL_PARAMETER_DEFS = {'ALL':
                      [('HX', 0.0, 1.0),
                       ('HY', -6.0, -3.5),
                       ('JX', -0.5, 0.0),
                       ('JA', -7.0, 0.0),
                       ('LP', -1.0, 1.0),
                       ('LD', -2.0, 4.0),
                       ('VS',  0.0, 1.0),
                       ('VO', -0.1, 1.0),
                       ('TCX', -3.0, 4.0),
                       ('TCY', -3.0, 1.0),
                       ('TTX', 1.5, 5.5),
                       ('TTY', -3.0, 2.5),
                       ('TBX', -3.0, 4.0),
                       ('TBY', -3.0, 5.0),
                       ('TRX', -4.0, 2.0),
                       ('TRY', -6.0, 0.0),
                       ('TS1', 0.0, 1.0),
                       ('TS2', 0.0, 1.0),
                       ('TS3', -1.0, 1.0)
                       ]
                      }
